# Generated by Django 5.0.2 on 2024-02-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cineulima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
