# Generated by Django 5.0.2 on 2024-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineulima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='banner',
            field=models.TextField(null=True),
        ),
    ]
