# Generated by Django 5.0.2 on 2024-02-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineulima', '0002_remove_usuario_id_alter_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
