# Generated by Django 5.0.2 on 2024-02-17 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineulima', '0002_recomendacionpelicula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacionpelicula',
            name='imgUrl',
        ),
        migrations.RemoveField(
            model_name='recomendacionpelicula',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='recomendacionpelicula',
            name='path',
        ),
        migrations.AddField(
            model_name='recomendacionpelicula',
            name='activo',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendacionpelicula',
            name='id_pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cineulima.pelicula'),
        ),
    ]
