# Generated by Django 5.0.2 on 2024-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineulima', '0002_usuariosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionPelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('enlace', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
