# Generated by Django 5.0.2 on 2024-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineulima', '0003_recomendacionpelicula_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendacionpelicula',
            old_name='enlace',
            new_name='imgUrl',
        ),
        migrations.AddField(
            model_name='recomendacionpelicula',
            name='path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
