# Generated by Django 5.0.2 on 2024-02-18 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineulima', '0004_ventana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cineulima.pelicula')),
                ('sala_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cineulima.sala')),
                ('ventana_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cineulima.ventana')),
            ],
        ),
    ]
